title: zdh's Homepage
page-top-title: "Software Engineerning"
top-section-bg-text: Be what you wanna be
home-subtitle: zdh&ensp;|&ensp;章东辉
copyright-text: '&copy; zdh 2023-2025. All Rights Reserved.'
